server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/yt_task_user_service
    username: root
    password: 08033468393dad
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/